---
- name: Apache_httpd | Install mod_jk prerequisites
  apt:
    package: "{{ apache_modjk_prerrequisites }}"
    update_cache: yes
    cache_valid_time: 86400

- name: Apache_httpd | Ensure mod_jk build directory
  file:
    path: "{{ apache_modjk_download_dir }}"
    state: directory

- name: Apache_httpd | Download mod_jk
  unarchive:
    src: "{{ apache_modjk_url }}"
    dest: "{{ apache_modjk_download_dir }}"
    remote_src: yes
  changed_when: false

- name: Apache_httpd | Create configure script
  command: ./buildconf.sh
  args:
    chdir: "{{ apache_modjk_build_dir }}"
  changed_when: false

- name: Apache_httpd | Configure mod_jk
  command: ./configure -with-apxs={{ apache_install_dir }}/bin/apxs
  args:
    chdir: "{{ apache_modjk_build_dir }}"
  changed_when: false

- name: Apache_httpd | Make mod_jk
  make:
    chdir: "{{ apache_modjk_build_dir }}"
  changed_when: false

- name: Apache_httpd | Set apache_modjk_so_files fact
  set_fact:
    apache_modjk_so_files: [ "{{ apache_modjk_build_dir }}/apache-2.0/mod_jk.so" ]

- name: Apache_httpd | Set apache_modules_so_files fact
  set_fact:
    apache_modules_so_files: "{{ apache_modules_so_files + apache_modjk_so_files if apache_modules_so_files is defined else apache_modjk_so_files }}"
